### ISSUE TITLE
Differences between yturl and youtube-dl

### ISSUE THREAD

**Issue by alphapapa** [cdown/yturl#24] opened 2015-10-22 00:31 UTC
Hi there, I found this through onethingwell.org.  I'm just curious, how do you see this project in relation to youtube-dl?

**Comment by cdown** [comment] 2015-10-22 08:09
Despite having similar names and providing some overlap in functionality, fundamentally youtube-dl and yturl are different projects with different goals. The development team of youtube-dl has worked a lot on supporting all sorts of sites (not just "youtube"), and all sorts of actions (not just "dl"). Case in point, just [the "extraction" code](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py) for YouTube alone is a little under 10x larger than the whole of yturl (caveat to GitHub's loc measuring system, and the fact that they put tests in their code, which is interesting).

Fundamentally many of the differences between yturl exist in terms of culture and design. I am very interested in building a tool that adheres to [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy), whereas youtube-dl has largely an unbounded scope and has a comparatively very large codebase. I also am not very interested in participating in a large project without a comprehensive test suite because it actively makes improvements more difficult -- my time to spend on open-source projects is already strained enough as it is (youtube-dl has around [29% test coverage](https://gist.github.com/cdown/007a2fe58681cf1a9210) according to `nosetests --with-coverage --cover-branches` on Python 3.5).

As for how yturl came about: 5 years ago or so, when the desire to stop using Flash was enough for me to want to find alternative options, youtube-dl was something that I considered. The main reason that I started writing yturl at first was because I encountered blocking bugs that actually stopped me from watching many videos (something which I assume they later fixed), and had been hindered in fixing them simply because of the state that the code was in at the time. If youtube-dl had worked for met then, probably yturl would never have come about.

That's not to detract from youtube-dl, it's (self-evidently, as judged by the number of people who use it) a useful project, released around 3 years before yturl, and yturl is by design not a 1:1 replacement for it (ie. it only does the "url" and "youtube" bits). The choice of which of these (or others!) to use is up to the user. :-)

**Comment by alphapapa** [comment] 2015-10-24 03:07
Cool, thanks.  I've been using youtube-dl in some scripts for a few years, but the way your script outputs the direct URL to the actual video file looks handy.

**Comment by cdown** [comment] 2015-10-24 09:07
I think youtube-dl can also do that with some flags, if I recall correctly. :-)

I'm going to close this out for now since there's not much actionable here, but thanks for the question -- it's good to get my thoughts about yturl/youtube-dl written down somewhere.

**Closed by cdown** 2015-10-24 09:07 UTC
